### ISSUE TITLE
urdf error

### ISSUE THREAD

**Issue by hejian1w** [Kinovarobotics/Kinova-kortex2_Gen3_G3L#155]
## Description
Data in ROS_KORTEX_NOETIC_DEVEL  kortex_description->arms->gen3 -> GEN3_YRDF_V12.urdf;  The urdf data in 7dof is inconsistent with the document （Homogeneous transform matrices - 7 DoF spherical wrist）, I want to use this urdf data to make IK and FK, I should refer to the data of the real robot arm GEN3, is this a bug

  <joint name="Actuator1" type="continuous">
    <origin xyz="0 0 0.15643" rpy="3.1416 2.7629E-18 -4.9305E-36" />

The XYZ data has some errors

**Comment by hejian1w** [comment]
> 
For example
urdf：  
<joint name="Actuator1" type="continuous">
    <origin xyz="0 0 0.15643" rpy="3.1416 2.7629E-18 -4.9305E-36" />

doc：
  0.1564

**Comment by rojikada** [comment]
If you want FK/IK you can use DH parameters. The base transformation is:
   ```
    1, 0,  0,   0,
    0,  -1, 0,   0,
    0,  0,  -1,  0,
    0,  0,  0,   1
```

and the end-effector is without any rotation and Z-axis is +0.120m.

**Comment by hejian1w** [comment]
I mean, in the document, the offset data is 4 decimal places, like 0.1564, while on the UDF file, it is 5 decimal places, 0.1564




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Adam ***@***.***&gt;; 
发送时间: 2023年3月7日(星期二) 凌晨4:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Kinovarobotics/kortex] urdf error (Issue #155)





 
If you want FK/IK you can use DH parameters. The base transformation is:
  1, 0,  0,   0,  0,  -1, 0,   0,  0,  0,  -1,  0,  0,  0,  0,   1  
and the end-effector is without any rotation and Z-axis is +0.120m.

**Comment by hejian1w** [comment]
I mean, in the document, the offset data is 4 decimal places, like 0.1564, while on the urdf file, it is 5 decimal places, 0.15643. What set of data should I end up with?






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kinovarobotics/kortex"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月7日(星期二) 凌晨4:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kinovarobotics/kortex] urdf error (Issue #155)





 
If you want FK/IK you can use DH parameters. The base transformation is:
  1, 0,  0,   0,  0,  -1, 0,   0,  0,  0,  -1,  0,  0,  0,  0,   1  
and the end-effector is without any rotation and Z-axis is +0.120m.

**Comment by hejian1w** [comment]
> 
When I use the example in the document, the calculated fk is inconsistent with the real robotic arm end data, which should be caused by some details

**Comment by hejian1w** [comment]
> If you want FK/IK you can use DH parameters from the documentation PDF. The base transformation is:
> 
> ```
>  1, 0,  0,   0,
>  0,  -1, 0,   0,
>  0,  0,  -1,  0,
>  0,  0,  0,   1
> ```
> 
> and the end-effector is without any rotation and Z-axis is +0.120m.

What is the source of the data?

**Comment by rojikada** [comment]
It comes from DH parameters inside the documentation. This is the 0-th parameter converted into transformation matrix.

**Comment by hejian1w** [comment]
> It comes from DH parameters inside the documentation. This is the 0-th parameter converted into transformation matrix.

Could you please supply a screenshot from Docs? I only found one matrix which contains transformation matrix of the base matrix you provided

**Comment by rojikada** [comment]
<img width="1253" alt="Snímek obrazovky 2023-03-13 v 18 24 21" src="https://user-images.githubusercontent.com/3816936/224779035-8400f0df-cdb7-4388-9a8e-0fab1278aecf.png">

**Comment by hejian1w** [comment]
> <img alt="Snímek obrazovky 2023-03-13 v 18 24 21" width="1253" src="https://user-images.githubusercontent.com/3816936/224779035-8400f0df-cdb7-4388-9a8e-0fab1278aecf.png">
> 
> from EN-UG-014-Gen3-Ultralight-user-guide-r8.pdf

My matrix is based on this, but your 0.120 does not have a value that represents the source of this data. Can you give me a contact information

**Comment by rojikada** [comment]
I see, 0.12 comes from different place:
![Uploading EAE1A0B9-C83D-46EA-B402-75F201B4A79B.jpeg…]()

**Comment by rojikada** [comment]
I see, 0.12 comes from different place:
![324CF5C1-6CA9-40F4-BFC4-99F29B3140D9](https://user-images.githubusercontent.com/3816936/224917708-611cbd8a-c5b1-40dc-8966-80c93273b39c.jpeg)

**Comment by hejian1w** [comment]
Thanks！I will check the data again.

**Comment by felixmaisonneuve** [comment]
Hi @hejian1w,

Were you able to find all the information you wanted in the Gen3 user guide?

Best,
Felix

**Comment by martinleroux** [comment]
Hi all,

I will be closing this issue since it seems to have been solved above.

However, for future reference to anyone ending up here, you should know that the URDF is the more accurate data - we limit the number of decimal places used in the User Guide for repeatability, but the URDF is generated directly from the CAD.

However, should you need so much precision that this very small difference matters, then you are going to face another issue in that the URDF model is an ideal one and does not take into consideration assembly tolerances. Each robot is calibrated, which explains why manually computing the kinematics outputs a value that differs from what is reported by the robot in the Web App. If you need information regarding the calibration parameters of your specific unit, please contact support@kinova.ca with the serial number of your arm (found on the sticker at the base - the value in the Web app is the SN of the controller, which is not what we are looking for) and we will find the calibration file of your robot in our archives.

Cheers
