### ISSUE TITLE
Missing utilities package

### ISSUE THREAD

**Issue by huythinhnguyen** [Kinovarobotics/Kinova-kortex2_Gen3_G3L#160]
https://github.com/Kinovarobotics/kortex/blob/44dac04e89f0ba8a6d8fc6b9e5e12c677e738c1e/api_python/examples/000-Getting_Started/01-api_creation.py#L71

Is a utilities package missing? I cannot run the examples

**Comment by felixmaisonneuve** [comment]
Hi @huythinhnguyen,

We change current directory on te line before. 
The Utilities.py files is supposed to be present : 
https://github.com/Kinovarobotics/kortex/blob/44dac04e89f0ba8a6d8fc6b9e5e12c677e738c1e/api_python/examples/utilities.py

Regards,
Felix
