### ISSUE TITLE
02-send_cartesian_waypoint_trajectory.py Unexpected Singularity Regions

### ISSUE THREAD

**Issue by keenan88** [Kinovarobotics/Kinova-kortex2_Gen3_G3L#198]
## Description

I am working with my gen3 arm, and running the 02-send_cartesian_waypoint_trajectory.py demo. When I run the waypoints in the demo, there are no problems. However, when I change the points to custom points that I know are within the arms dextrous workspace, the script outputs SINGULARITY_REGION errors. Sometimes, the arm will stop moving when the singularity region errors occurs, and sometimes it will get to the waypoint, and then no further waypoints.

## Version

At a minimum, provide the Kortex API and Kortex-enabled device versions.

KortexAPI : 2.6.0

Kortex Device : Gen3 running the latest firmware
![image](https://github.com/Kinovarobotics/kortex/assets/45887966/8f9c07fa-cca5-4bb9-9a8c-dd53db332950)

## Steps to reproduce

Run the python file below on a gen3 arm. Modify the IP address of the arm, if needed.

## Code example

The following python file is a copy of https://github.com/Kinovarobotics/kortex/blob/master/api_python/examples/110-Waypoints/02-send_cartesian_waypoint_trajectory.py. I have changed check_for_end_or_abort to print the entire notification, commented out the blended trajectory execution, set the arm's IP to 192.168.1.10, and overwritten the waypointsDefinition tuple to contain a single waypoint that I obtained from the web interface.

[02-send_cartesian_waypoint_trajector.txt](https://github.com/user-attachments/files/15992895/02-send_cartesian_waypoint_trajector.txt)

## Expected behavior

The arm should be able to reach the single custom waypoint without throwing any singularity errors.

## Actual behaviour

The first trajectory is the default trajectory in the example. I moved the X values back to 0.5, since I have a mast in front of the arm. The trajectory executes without problems.

The second trajectory is the output when I try to send the arm to my custom waypoint. Partway thru, there is an inverse kinematics/singularity region error, and the arm stops moving.

[First_traj_output.txt](https://github.com/user-attachments/files/15992821/First_traj_output.txt)
[second_traj_output.txt](https://github.com/user-attachments/files/15992890/second_traj_output.txt)

Thank you,

Keenan

**Comment by martinleroux** [comment]
Hi Keenan,

The pose you are commanding the robot is directly into a wrist singularity. The behaviour you are describing is intended. As a workaround, you can reach this pose with an angular command. Note that once in this pose, you will also need an angular command to get out since the kinematics will not converge when the pose is singular.

Cheers
